ctripcorp/SQLlin

- sqllin-driver/README.md
- sqllin-dsl/doc/advanced-query.md
> Fix some English docs

- .github/workflows/build.yml
- .github/workflows/publish.yml
- test_android.sh
- test_driver_macos.sh
- test_driver_windows.sh
- test_dsl_macos.sh
- test_dsl_windows.sh
Add the instrumentation tests to workflow.
> Add the instrumentation tests to workflow

- README.md
- README_CN.md
Add some explanation about serialization and deserialization.
> Fix the README

- .github/workflows/build.yml
- .github/workflows/publish.yml
- README.md
- README_CN.md
- publish_windows.sh
- sample/build.gradle.kts
- sqllin-driver/build.gradle.kts
- sqllin-driver/src/appleTest/kotlin/com/ctrip/sqllin/driver/PlatformApple.kt
- sqllin-driver/src/linuxTest/kotlin/com/ctrip/sqllin/driver/PlatformLinux.kt
- sqllin-driver/src/mingwTest/kotlin/com/ctrip/sqllin/driver/PlatformMingw.kt
- sqllin-driver/src/nativeTest/kotlin/com/ctrip/sqllin/driver/NativeTest.kt
- sqllin-driver/src/nativeTest/kotlin/com/ctrip/sqllin/driver/Platform.kt
- sqllin-dsl/build.gradle.kts
- sqllin-dsl/src/appleTest/kotlin/com/ctrip/sqllin/dsl/PlatformApple.kt
- sqllin-dsl/src/linuxTest/kotlin/com/ctrip/sqllin/dsl/PlatformLinux.kt
- sqllin-dsl/src/mingwTest/kotlin/com/ctrip/sqllin/dsl/PlatformMingw.kt
- sqllin-dsl/src/nativeTest/kotlin/com/ctrip/sqllin/dsl/NativeTest.kt
- sqllin-dsl/src/nativeTest/kotlin/com/ctrip/sqllin/dsl/Platform.kt
- test_driver_windows.sh
- test_dsl_windows.sh
Support unit test on different desktop platform.
> Support unit test on different desktop platform

- build.gradle.kts
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- sample/build.gradle.kts
- settings.gradle.kts
Because of the problem about publishing, downgrade the Gradle and AGP versions.
> Downgrade the Gradle and AGP versions

- sqllin-driver/build.gradle.kts
- sqllin-driver/src/appleTest/kotlin/com/ctrip/sqllin/driver/PlatformApple.kt
- sqllin-driver/src/commonTest/kotlin/com/ctrip/sqllin/driver/CommonBasicTest.kt
- sqllin-driver/src/linuxTest/kotlin/com/ctrip/sqllin/driver/PlatformLinux.kt
- sqllin-driver/src/mingwTest/kotlin/com/ctrip/sqllin/driver/PlatformMingw.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/ConnectionExtension.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/ExtensionNative.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/RealDatabaseConnection.kt
- sqllin-driver/src/nativeTest/kotlin/com/ctrip/sqllin/driver/NativeTest.kt
- sqllin-driver/src/nativeTest/kotlin/com/ctrip/sqllin/driver/Platform.kt
- sqllin-dsl/build.gradle.kts
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/compiler/EncodeEntities2SQL.kt
Fix the problem that about Windows' unit tests can't pass.
> Fix the problem about Windows' unit tests can't pass

- CHANGELOG.md
- sqllin-driver/src/androidMain/kotlin/com/ctrip/sqllin/driver/CursorImpl.kt
- sqllin-driver/src/androidMain/kotlin/com/ctrip/sqllin/driver/DatabaseConnectionImpl.kt
- sqllin-driver/src/commonMain/kotlin/com/ctrip/sqllin/driver/CommonCursor.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/ConcurrentDatabaseConnection.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/CursorImpl.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/NativeDatabaseConnection.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/RealDatabaseConnection.kt
Add the new function 'close' and lead some unnecessary APIs be internal.
> Add the new function 'close' and lead some unnecessary APIs be internal

- CHANGELOG.md
- README.md
- README_CN.md
- gradle.properties
- sample/build.gradle.kts
- sqllin-driver/README.md
- sqllin-driver/README_CN.md
- sqllin-driver/build.gradle.kts
- sqllin-driver/src/androidMain/kotlin/com/ctrip/sqllin/driver/ExtensionAndroid.kt
- sqllin-dsl/build.gradle.kts
Add the `watchosDeviceArm64` support. Update `kotlinx.serialization`'s version.
> Add the watchosDeviceArm64 support

- .github/workflows/build.yml
- .github/workflows/publish.yml
- CHANGELOG.md
- sqllin-driver/build.gradle.kts
- sqllin-dsl/build.gradle.kts
Disabled some publishing tasks on incorrect platforms.
> Disabled some publishing tasks on incorrect platforms

- .github/workflows/build.yml
- .github/workflows/publish.yml
- CHANGELOG.md
- sqllin-dsl/doc/advanced-query-cn.md
- sqllin-dsl/doc/advanced-query.md
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/statement/SingleStatement.kt
Add 'cache' step for CI/CD, and fix some docs.
> Add 'cache' step for CI/CD

- .github/workflows/build.yml
- .github/workflows/publish.yml
- sqllin-driver/build.gradle.kts
- sqllin-dsl/build.gradle.kts
- test_android.sh
Add the uninstalling commands before execute the Android instrumented tests.
> Add the uninstalling commands before execute the Android instrumented tests

- README.md
- README_CN.md
Fix the READMEs of the project.
> Fix the READMEs of the project

- CHANGELOG.md
- gradle.properties
- sqllin-driver/build.gradle.kts
- sqllin-driver/src/appleMain/kotlin/com/ctrip/sqllin/driver/platform/UtilsApple.kt
- sqllin-driver/src/linuxMain/kotlin/com/ctrip/sqllin/driver/platform/Lock.kt
- sqllin-driver/src/linuxMain/kotlin/com/ctrip/sqllin/driver/platform/UtilsLinux.kt
- sqllin-driver/src/linuxTest/kotlin/com/ctrip/sqllin/driver/PlatformLinux.kt
- sqllin-driver/src/mingwMain/kotlin/com/ctrip/sqllin/driver/platform/Lock.kt
- sqllin-driver/src/mingwMain/kotlin/com/ctrip/sqllin/driver/platform/UtilsMinGW.kt
- sqllin-driver/src/mingwTest/kotlin/com/ctrip/sqllin/driver/PlatformMingw.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/RealDatabaseConnection.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/SQLiteException.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/cinterop/NativeDatabase.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/cinterop/NativeStatement.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/platform/Utils.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/Database.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/statement/SelectStatement.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/statement/Stack.kt
- sqllin-dsl/src/linuxTest/kotlin/com/ctrip/sqllin/dsl/PlatformLinux.kt
- sqllin-dsl/src/mingwTest/kotlin/com/ctrip/sqllin/dsl/PlatformMingw.kt
- sqllin-processor/src/main/kotlin/com/ctrip/sqllin/processor/ClauseProcessor.kt
Fix some bugs about Kotlin update
> Fix some bugs about Kotlin update

- README.md
- README_CN.md
- gradle.properties
- sample/build.gradle.kts
- sqllin-driver/build.gradle.kts
- sqllin-dsl/build.gradle.kts
- sqllin-dsl/doc/getting-start-cn.md
- sqllin-dsl/doc/getting-start.md
Fix some docs and build scripts.
> Fix some docs and build scripts

- sqllin-driver/build.gradle.kts
- sqllin-driver/src/appleMain/kotlin/com/ctrip/sqllin/driver/platform/UtilsApple.kt
- sqllin-driver/src/linuxMain/kotlin/com/ctrip/sqllin/driver/platform/UtilsLinux.kt
- sqllin-driver/src/mingwMain/kotlin/com/ctrip/sqllin/driver/platform/UtilsMinGW.kt
- sqllin-driver/src/nativeMain/kotlin/com/ctrip/sqllin/driver/platform/Utils.kt
- sqllin-dsl/build.gradle.kts
- sqllin-processor/src/main/kotlin/com/ctrip/sqllin/processor/ClauseProcessor.kt
Optimize the sqllin-procrssor's process
> Optimize the sqllin-procrssor's process

- .github/workflows/build.yml
- sqllin-dsl/src/commonTest/kotlin/com/ctrip/sqllin/dsl/CommonBasicTest.kt
Add the New JVM Target, and fix the error in unit tests.
> Add the New JVM Target

- test_android.sh
Modify the android instrumented tests shell script.
> Modify the android instrumented tests shell script

- sqllin-dsl/doc/getting-start-cn.md
- sqllin-dsl/doc/getting-start.md
Add the information about linkerOpts into doc 'Getting Start'.
> Add the information about linkerOpts into doc 'Getting Start'

- sqllin-dsl/doc/getting-start-cn.md
- sqllin-dsl/doc/getting-start.md
> Fix the docs

- sqllin-driver/build.gradle.kts
- sqllin-dsl/build.gradle.kts
Try to fix the publishing failed.
> Try to fix the publishing failed

- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/DatabaseScope.kt
- sqllin-dsl/src/commonTest/kotlin/com/ctrip/sqllin/dsl/Entities.kt
- sqllin-dsl/src/commonTest/kotlin/com/ctrip/sqllin/dsl/TestPrimitiveTypeForKSP.kt
> Fix some comments

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- sample/build.gradle.kts
- sqllin-driver/build.gradle.kts
- sqllin-dsl/build.gradle.kts
- sqllin-processor/build.gradle.kts
> Update version to 1.2.4

- sqllin-driver/README.md
- sqllin-driver/README_CN.md
- sqllin-dsl/doc/getting-start-cn.md
- sqllin-dsl/doc/getting-start.md
- sqllin-processor/build.gradle.kts
> Fix some documents

- sqllin-processor/build.gradle.kts
Fix the published script of sqllin-processor.
> Fix the published script of sqllin-processor

- .github/workflows/build.yml
- sqllin-driver/src/commonMain/kotlin/com/ctrip/sqllin/driver/Extension.kt
Add the emulator-build param into build.yml.
> Add the emulator-build param into build.yml

- .github/workflows/build.yml
- .github/workflows/publish.yml
- restart_adb_server.sh
> Add the adb restart commands

- sqllin-driver/build.gradle.kts
- sqllin-dsl/build.gradle.kts
Fix the problem that can't publish to Maven.
> Fix the problem that can't publish to Maven

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- sample/build.gradle.kts
- settings.gradle.kts
- sqllin-driver/build.gradle.kts
- sqllin-dsl/build.gradle.kts
- sqllin-processor/build.gradle.kts
Update the dependencies management.
> Update the dependencies management

- CHANGELOG.md
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- sqllin-dsl/doc/getting-start-cn.md
- sqllin-dsl/doc/getting-start.md
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/DatabaseScope.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/annotation/DslMaker.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/BaseJoinClause.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/ConditionClause.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/CrossJoinClause.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/Function.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/GroupByClause.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/HavingClause.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/InnerJoinClause.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/LeftOuterJoinClause.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/LimitClause.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/OrderByClause.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/SetClause.kt
- sqllin-dsl/src/commonMain/kotlin/com/ctrip/sqllin/dsl/sql/clause/WhereClause.kt
- sqllin-processor/src/main/kotlin/com/ctrip/sqllin/processor/ClauseProcessor.kt
> Update version to 1.4.1

- .github/workflows/build.yml
- .github/workflows/publish.yml
- CHANGELOG.md
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- sample/build.gradle.kts
- sqllin-driver/build.gradle.kts
- sqllin-dsl/build.gradle.kts
- sqllin-dsl/doc/concurrency-safety-cn.md
- sqllin-dsl/doc/concurrency-safety.md
- sqllin-dsl/doc/getting-start-cn.md
- sqllin-dsl/doc/getting-start.md
* Update `Kotlin`'s version to `2.1.20`
* Update `kotlinx.coroutines`'s version to `1.10.2`
* Update `kotlinx.serialization`'s version to `1.8.1`
* Update the `sqlite-jdbc`'s version to `3.49.1.0`
* Update `KSP`'s version to `2.1.20-1.0.32`
> Update version to 1.4.2
